app-id: cn.xfangfang.wiliwili
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: wiliwili
copy-icon: true
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --device=all
  - --share=network
  - --socket=pulseaudio
  - --filesystem=home/.var/app/cn.xfangfang.wiliwili/config:create
  - --filesystem=xdg-run/pipewire-0:ro
  - --talk-name=org.freedesktop.ScreenSaver
  - --talk-name=org.freedesktop.PowerManagement
  - --talk-name=org.gnome.SessionManager
  - --talk-name=org.mate.SessionManager
  - --env=LC_NUMERIC=C
modules:
  - name: wiliwili
    buildsystem: cmake-ninja
    config-opts:
      - '-DPLATFORM_DESKTOP=ON'
      - '-DUSE_SYSTEM_CURL=ON'
      - '-DINSTALL=ON'
      - '-DCMAKE_BUILD_TYPE=Release'
    builddir: true
    sources:
      - type: dir
        path: '.'
    modules:
      - name: libmpv
        cleanup:
          - /include
          - /lib/pkgconfig
          - /share/man
        buildsystem: meson
        config-opts:
          - -Dlibmpv=true
          - -Dlua=disabled
          - -Ddebug=false
          - -Dbuild-date=false
          - -Dalsa=disabled
          - -Dcplayer=false
          - -Dmanpage-build=disabled
        sources:
          - type: archive
            url: https://github.com/mpv-player/mpv/archive/refs/tags/v0.36.0.tar.gz
            sha256: 29abc44f8ebee013bb2f9fe14d80b30db19b534c679056e4851ceadf5a5e8bf6
        modules:
          - name: libv4l2
            cleanup:
              - /sbin
              - /bin
              - /include
              - /lib/*.la
              - /lib/*/*.la
              - /lib*/*/*/*.la
              - /lib/pkgconfig
              - /share/man
            config-opts:
              - '--disable-static'
              - '--disable-bpf'
              - '--with-udevdir=/app/lib/udev'
            sources:
              - type: archive
                url: 'https://linuxtv.org/downloads/v4l-utils/v4l-utils-1.24.1.tar.bz2'
                sha256: 'cbb7fe8a6307f5ce533a05cded70bb93c3ba06395ab9b6d007eb53b75d805f5b'

          - name: nv-codec-headers
            cleanup:
              - '*'
            no-autogen: true
            make-install-args:
              - PREFIX=/app
            sources:
              - type: archive
                url: 'https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n12.1.14.0.tar.gz'
                sha256: '2fefaa227d2a3b4170797796425a59d1dd2ed5fd231db9b4244468ba327acd0b'

          - name: ffmpeg
            cleanup:
              - /include
              - /lib/pkgconfig
              - /share/ffmpeg/examples
            config-opts:
              - '--enable-shared'
              - '--disable-static'
              - '--enable-gnutls'
              - '--enable-gpl'
              - '--disable-doc'
              - '--disable-programs'
              - '--disable-encoders'
              - '--disable-muxers'
              - '--enable-encoder=png,libwebp'
              - '--enable-libv4l2'
              - '--enable-libdav1d'
              - '--enable-libfontconfig'
              - '--enable-libfreetype'
              - '--enable-libopus'
              - '--enable-librsvg'
              - '--enable-libvpx'
              - '--enable-libmp3lame'
              - '--enable-libwebp'
            sources:
              - type: archive
                url: 'https://ffmpeg.org/releases/ffmpeg-6.0.tar.gz'
                sha256: 'f4ccf961403752c93961927715f524576d1f4dd02cd76d8c76aed3bbe6686656'

          - name: libass
            cleanup:
              - /include
              - /lib/*.la
              - /lib/pkgconfig
            config-opts:
              - '--disable-static'
            sources:
              - type: archive
                url: 'https://github.com/libass/libass/releases/download/0.17.1/libass-0.17.1.tar.gz'
                sha256: 'd653be97198a0543c69111122173c41a99e0b91426f9e17f06a858982c2fb03d'

          - name: uchardet
            buildsystem: cmake-ninja
            config-opts:
              - '-DCMAKE_BUILD_TYPE=Release'
              - '-DBUILD_STATIC=0'
            cleanup:
              - /bin
              - /include
              - /lib/pkgconfig
              - /share/man
            sources:
              - type: archive
                url: 'https://gitlab.freedesktop.org/uchardet/uchardet/-/archive/v0.0.8/uchardet-v0.0.8.tar.gz'
                sha256: '5aa402a1b5b1dbb8d81096f141ff1224e079f4d3a1db0f79ecca782756d3a416'

      - name: libwebp
        config-opts: [ --disable-static, --enable-libwebpmux, --enable-libwebpdemux ]
        cleanup: [ /share, /bin, /include ]
        sources:
          - type: archive
            url: https://github.com/webmproject/libwebp/archive/refs/tags/v1.3.0.tar.gz
            sha256: dc9860d3fe06013266c237959e1416b71c63b36f343aae1d65ea9c94832630e1
            x-checker-data:
              type: anitya
              project-id: 1761
              url-template: https://github.com/webmproject/libwebp/archive/refs/tags/v$version.tar.gz
              is-important: true
