app-id: cn.xfangfang.wiliwili
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: wiliwili
finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  # This program is designed for controller
  - --device=all
  - --share=network
  - --socket=pulseaudio
  # inhibiting screen saver
  - --talk-name=org.freedesktop.ScreenSaver
  - --talk-name=org.freedesktop.PowerManagement
  - --talk-name=org.gnome.SessionManager
  - --talk-name=org.mate.SessionManager
  # control steam client
  - --filesystem=~/.steam
cleanup-commands:
  - mkdir -p /app/lib/ffmpeg
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/pkgconfig
  - /man
  - /share/man
  - /share/gtk-doc

modules:

  - name: libmpv
    buildsystem: meson
    config-opts:
      - -Dlibmpv=true
      - -Dlua=enabled
      - -Ddebug=false
      - -Dbuild-date=false
      - -Dcplayer=false
      - -Dmanpage-build=disabled
    sources:
      - type: archive
        url: https://github.com/mpv-player/mpv/archive/refs/tags/v0.39.0.tar.gz
        sha256: 2ca92437affb62c2b559b4419ea4785c70d023590500e8a52e95ea3ab4554683
        x-checker-data:
          type: anitya
          project-id: 5348
          stable-only: true
          url-template: https://github.com/mpv-player/mpv/archive/refs/tags/v$version.tar.gz
    modules:

      - name: libXpresent
        buildsystem: autotools
        sources:
          - type: archive
            url: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-1.0.1.tar.xz
            sha256: b964df9e5a066daa5e08d2dc82692c57ca27d00b8cc257e8e960c9f1cf26231b
            x-checker-data:
              type: anitya
              project-id: 17166
              stable-only: true
              url-template: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-$version.tar.xz

      - name: luajit
        no-autogen: true
        cleanup:
          - /bin
          - /include
          - /lib/pkgconfig
          - /share/man
        sources:
          - type: git
            url: https://github.com/LuaJIT/LuaJIT.git
            mirror-urls:
              - https://luajit.org/git/luajit.git
            disable-shallow-clone: true
            commit: 97813fb924edf822455f91a5fbbdfdb349e5984f
            x-checker-data:
              type: json
              url: https://api.github.com/repos/LuaJIT/LuaJIT/commits
              commit-query: first( .[].sha )
              version-query: first( .[].sha )
              timestamp-query: first( .[].commit.committer.date )
          - type: shell
            commands:
              - sed -i 's|/usr/local|/app|' ./Makefile

      - name: nv-codec-headers
        cleanup:
          - '*'
        no-autogen: true
        make-install-args:
          - PREFIX=/app
        sources:
          - type: archive
            url: https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n12.2.72.0.tar.gz
            sha256: dbeaec433d93b850714760282f1d0992b1254fc3b5a6cb7d76fc1340a1e47563
            x-checker-data:
              type: anitya
              project-id: 223796
              stable-only: true
              url-template: https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n$version.tar.gz

      - name: libass
        config-opts:
          - --disable-static
        sources:
          - type: archive
            url: https://github.com/libass/libass/releases/download/0.17.3/libass-0.17.3.tar.gz
            sha256: da7c348deb6fa6c24507afab2dee7545ba5dd5bbf90a137bfe9e738f7df68537
            x-checker-data:
              type: anitya
              project-id: 1560
              stable-only: true
              url-template: https://github.com/libass/libass/releases/download/$version/libass-$version.tar.gz

      - name: uchardet
        buildsystem: cmake-ninja
        config-opts:
          - -DCMAKE_BUILD_TYPE=Release
          - -DBUILD_STATIC=0
        sources:
          - type: archive
            url: https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.8.tar.xz
            sha256: e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
            x-checker-data:
              type: anitya
              project-id: 9265
              stable-only: true
              url-template: https://www.freedesktop.org/software/uchardet/releases/uchardet-$version.tar.xz

      - name: libplacebo
        buildsystem: meson
        config-opts:
          - -Dglslang=disabled
          - -Dd3d11=disabled
          - -Ddemos=false
        sources:
          - type: git
            url: https://github.com/haasn/libplacebo.git
            commit: 1fd3c7bde7b943fe8985c893310b5269a09b46c5
            tag: v7.349.0
            x-checker-data:
              type: git
              tag-pattern: ^v([\d.]+)$

      - name: ffmpeg
        cleanup:
          - /include
          - /lib/pkgconfig
          - /share/ffmpeg/examples
        config-opts:
          - --disable-debug
          - --enable-shared
          - --disable-static
          - --enable-gnutls
          - --enable-gpl
          - --disable-doc
          - --disable-programs
          - --disable-encoders
          - --disable-muxers
          - --enable-encoder=png
          - --enable-libdav1d
          - --enable-libfontconfig
          - --enable-libfreetype
          - --enable-libopus
          - --enable-librsvg
          - --enable-libvpx
          - --enable-libmp3lame

        sources:
          - type: git
            url: https://github.com/FFmpeg/FFmpeg.git
            mirror-urls:
              - https://git.ffmpeg.org/ffmpeg.git
            commit: b08d7969c550a804a59511c7b83f2dd8cc0499b8
            tag: n7.1
            x-checker-data:
              type: git
              tag-pattern: ^n([\d.]{3,7})$

  - name: wiliwili
    buildsystem: cmake-ninja
    config-opts:
      - -DPLATFORM_DESKTOP=ON
      - -DINSTALL=ON
      - -DCMAKE_BUILD_TYPE=Release
      - -DGLFW_BUILD_WAYLAND=ON
      - -DGLFW_BUILD_X11=ON
      - -DUSE_SYSTEM_CURL=ON
      - -DUSE_GLES2=OFF
      - -DBRLS_UNITY_BUILD=ON
      - -DCMAKE_UNITY_BUILD_BATCH_SIZE=16
    builddir: true
    sources:
      - type: dir
        path: '.'
