cmake_minimum_required(VERSION 3.15)

if (CMAKE_BUILD_TYPE STREQUAL Debug)
    add_definitions(-D_DEBUG)
    add_definitions(-D_GLIBCXX_ASSERTIONS)
    if (DEBUG_SANITIZER)
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -O0 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O0 -O0 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined,address")
    endif ()
endif ()

if (APPLE AND NOT PLATFORM_IOS)
    if (MAC_IntelChip)
        message(STATUS "CMAKE_OSX_ARCHITECTURES: x86_64")
        message(STATUS "CMAKE_OSX_DEPLOYMENT_TARGET: 10.11")
        set(CMAKE_OSX_ARCHITECTURES "x86_64" CACHE STRING "" FORCE)
        set(CMAKE_OSX_DEPLOYMENT_TARGET "10.11" CACHE STRING "" FORCE)

        set(USE_BOOST_FILESYSTEM ON)
    endif ()
    if(MAC_AppleSilicon)
        # Build a Universal binary on macOS
        message(STATUS "CMAKE_OSX_ARCHITECTURES: arm64")
        set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "" FORCE)
        set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "" FORCE)
    endif()
    if(MAC_Universal)
        # Build a Universal binary on macOS
        message(STATUS "CMAKE_OSX_ARCHITECTURES: x86_64;arm64")
        set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64" CACHE STRING "" FORCE)
        set(CMAKE_OSX_DEPLOYMENT_TARGET "10.11" CACHE STRING "" FORCE)
        set(CMAKE_XCODE_ATTRIBUTE_MACOSX_DEPLOYMENT_TARGET[arch=arm64] "11.0" CACHE STRING "" FORCE)

        set(USE_BOOST_FILESYSTEM ON)
    endif()
endif()

if (USE_BOOST_FILESYSTEM)
    set(CPR_USE_BOOST_FILESYSTEM ON)
    add_definitions(-DCPR_USE_BOOST_FILESYSTEM)
    add_definitions(-DUSE_BOOST_FILESYSTEM)
endif ()
