name: Build uwp wiliwili

on:
  push:
    branches:
      - uwp
      - dev
  workflow_dispatch:
    inputs:
      release:
        description: 'Push a new release'
        required: false
        default: 'false'
      version:
        description: 'Version'
        required: false
        default: '0.0.0'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      standard_version: ${{ steps.info.outputs.standard_version }}
      DIST_UWP: ${{ steps.info.outputs.DIST_UWP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name: Debug version
        run: |
          export VERSION=`git rev-parse --short HEAD`
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Release version
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()
        run: |
          export VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Version
        id: info
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "DIST_UWP=wiliwili-windows-x64-uwp-${VERSION}" >> $GITHUB_OUTPUT
          echo $VERSION
          echo "${{ github.event.inputs.version }}"
  build-win-x64:
    needs: [ version ]
    runs-on: windows-2022
    steps:
      - name: Setup Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 20348
      - name: Install NSIS
        shell: powershell
        run: |
          Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
          xmake --version
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pre-repo
        shell: powershell
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          xmake repo -a local https://github.com/zeromake/xrepo.git
          mkdir -p dist
          mkdir -p build/xrepo
          cd build/xrepo
          git clone https://github.com/xfangfang/borealis.git -b wiliwili --depth=1
          cd ../../
      - name: build
        shell: powershell
        env:
          VERSION: ${{ needs.version.outputs.VERSION }}
        run: |
          $env:path+=";C:\Users\$($env:username)\xmake"
          xmake f -c -y --sw=y --winrt=y --window=sdl --driver=d3d11
          xmake build wiliwili
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.version.outputs.DIST_UWP }}
          path: build/wiliwili.msix
